owner: iceeburr
repo: uptime-monitor
user-agent: iceeburr

skipDeleteIssues: true

sites:
  - name: iceeburr のラジオ
    method: GET
    url: https://iceeburr.dev/api/status
    icon: https://raw.githubusercontent.com/iceeburr/uptime-monitor/refs/heads/master/assets/favicon.png
  - name: Minecraft Server
    check: "tcp-ping"
    port: 25565
    url: play.iceeburr.dev
    icon: https://raw.githubusercontent.com/iceeburr/uptime-monitor/refs/heads/master/assets/minecraft_favicon.png
  - name: VPN Service
    url: https://veil.iceeburr.dev/dashboard
    icon: https://raw.githubusercontent.com/iceeburr/uptime-monitor/refs/heads/master/assets/vpn_favicon.png

status-website:
  cname: status.iceeburr.dev
  theme: dark
  logoUrl: https://raw.githubusercontent.com/iceeburr/uptime-monitor/refs/heads/master/assets/favicon.png
  favicon: https://raw.githubusercontent.com/iceeburr/uptime-monitor/refs/heads/master/assets/favicon.png
  name: iceeburr.dev
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - iceeburr

workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * 1"
  updates: "0 0 * * 1"
  uptime: "*/5 * * * *"
